version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./Backend
    depends_on:
      - db
    volumes:
      - ./Backend:/usr/app
      - /usr/app/node_modules
    ports: ['5000:5000']

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - '8081:8081'