version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./Backend
    volumes:
      - ./Backend:/usr/app
      - /usr/app/node_modules
    ports: ['5000:5000']

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - '8081:8081'